# Setup
title:               The Kernal
tagline:             'Guy With A Computer'
description:         '<img src="/images/86623542" alt="Logo">
<b>The best place on the internet for information related to Linux and Linux based operating systems</b>'
url:                 https://thekernal.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              TheKernal
  url:               https://lemmy.ml/u/TheKernalBlog
  email:             https://TheKernalBlog@protonmail.com 

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

